### ISSUE TITLE
Blog + Docs + Website Architecture

### ISSUE THREAD

**Issue by adrianoapmartins** [reviewpad/website#5]
It was discussed that Docusaurus is not the way to go for our website. Probably Next.js, but @ferreiratiago  will look into what's better.

**Comment by adrianoapmartins** [comment]
@ferreiratiago any news in this direction?
While acclimatizing to NextJS I bumped into their templates page where they feature quite a lot of solutions: https://vercel.com/templates?search=blog&framework=next.js

There's also Strapi, a blogging framework for NextJS that can be deployed on Vercel as well: https://market.strapi.io/plugins/strapi-plugin-vercel-deploy

**Comment by adrianoapmartins** [comment]
Thinking about the infrastructure I'm not so sure about having the blog on the documentation repository is the best logical architecture (even though technically could be easier).

Maybe we could instead have a separate repository and system for the blog alone, like Ghost.

Thinking about it, we could highly benefit from simply having the blog on Hashnode with a custom domain. [Medium vs Substack vs Hashnode](https://hashnode.com/vs/medium-substack)

**Comment by adrianoapmartins** [comment]
@ferreiratiago, just to close this issue, we decided to host the blog with NextJS on `www.reviewpad.com`, and the documentation with Docusaurs separately on `docs.reviewpad.com`, correct?

**Comment by ferreiratiago** [comment]
That is correct.
